### PR TITLE
Run the cursor on interactive mode

### PR DESCRIPTION
**Pull request by agatan**
Run the cursor by one key press
- to the point that has some branchws.
- to the point that is next to a wall.

w3ti4isfpl

### CODE REVIEW

**Comment by itchyny** [comment]
Thank you for submitting a pull request. But I think this feature should be an option, off by default.

**Comment by agatan** [comment]
Thank you for your mention.
Now that you mention it, I agree it.

I fixed it, but I'm not sure if the implementation is clean.
I wonder if the `Maze` should contain the `--run-cursor`'s value.

**Comment by itchyny** [comment]
I don't like multi-word options. Do you have any suggestion for one-word option name?

**Comment by agatan** [comment]
How about `--move=smart` ?

**Pull request closed without merging**
